spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        auto_quote_keyword: false
        highlight_sql: false
        show_sql: false
        format_sql: false
  config:
    import: optional:file:.env[.properties]

#  servlet:
#    multipart:
#      max-file-size: 5MB
#      max-request-size: 5MB
#      enabled: true

#cloud:
#  aws:
#    s3:
#      bucket: ${S3_BUCKET}
#    credentials:
#      accessKey: ${S3_PUBLIC}
#      secretKey: ${S3_SECRET}
#    region:
#      static: ${S3_REGION}
#    stack:
#      auto: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
