spring:
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        auto_quote_keyword: true
        highlight_sql: true
        show_sql: true
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  config:
    import: optional:file:.env[.properties]
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
      enabled: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${spring_mail_username}
    password: ${spring_mail_password}
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  data:
    redis:
      host: localhost
      port: 6379

cloud:
  aws:
    s3:
      bucket: ${S3_BUCKET}
    credentials:
      accessKey: ${S3_PUBLIC}
      secretKey: ${S3_SECRET}
    region:
      static: ${S3_REGION}
    stack:
      auto: false

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace

payment:
  kakao:
    secret:
      key: ${PAYMENT_KAKAO_SECRET_KEY}
    cid: ${PAYMENT_KAKAO_CID}

kakao:
  client_id: ${KAKAO_REST_API_KEY}
  redirect_uri: ${KAKAO_REDIRECT_URL}
