name: ci pipelines

on:
  pull_request:
    branches:
      - dev
  push:
    branches: [ dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.17.16
        ports:
          - 9200:9200
        options: --env discovery.type=single-node
      redis:
        image: redis
        ports:
          - 6379:6379
      logstash:
        image: docker.elastic.co/logstash/logstash:7.17.16
        ports:
          - 5001:5001
        options: >
          --env LS_JAVA_OPTS="-Xmx256m -Xms256m" 
          --env LS_CONFIG=/usr/share/logstash/pipeline/logstash.conf

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Create Logstash configuration
        run: |
          mkdir -p logstash/pipeline
          echo '
          input {
            tcp {
              port => 5001
              codec => json
            }
          }
          output {
            stdout {}
          }
          ' > logstash/pipeline/logstash.conf

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Clean generated sources
        run: rm -rf src/main/generated

      - name: Build project
        run: ./gradlew build -x test

      - name: Run test
        env:
          SPRING_PROFILES_ACTIVE: test
          LOGSTASH_HOST_TEST: logstash
          LOGSTASH_PORT_TEST: 5001
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          SPRING_MAIL_USERNAME: ${{ secrets.SPRING_MAIL_USERNAME }}
          SPRING_MAIL_PASSWORD: ${{ secrets.SPRING_MAIL_PASSWORD }}
          S3_BUCKET: ${{ secrets.S3_BUCKET }}
          S3_PUBLIC: ${{ secrets.S3_PUBLIC }}
          S3_SECRET: ${{ secrets.S3_SECRET }}
          S3_REGION: ${{ secrets.S3_REGION }}
          PAYMENT_KAKAO_SECRET_KEY: ${{ secrets.PAYMENT_KAKAO_SECRET_KEY }}
          PAYMENT_KAKAO_CID: ${{ secrets.PAYMENT_KAKAO_CID }}
          KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
          KAKAO_REDIRECT_URL: ${{ secrets.KAKAO_REDIRECT_URL }}
          NAVER_REST_API_KEY: ${{ secrets.NAVER_REST_API_KEY }}
          NAVER_REDIRECT_URL: ${{ secrets.NAVER_REDIRECT_URL }}
          NAVER_CLIENT_SECRET_KEY: ${{ secrets.NAVER_CLIENT_SECRET_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SPRING_MAIL_HOST: ${{ secrets.SPRING_MAIL_HOST }}
          SPRING_MAIL_PORT: ${{ secrets.SPRING_MAIL_PORT }}
          REDIS_HOST: localhost
          REDIS_PORT: 6379
          ELASTIC_URL: localhost:9200
          ADMIN_CREDENTIALS: ${{ secrets.ADMIN_CREDENTIALS }}
        run: ./gradlew test -Dspring.profiles.active=test
